### ISSUE TITLE
iOS 10.1 Safari doesn't seem to loadTexture from data uris

### ISSUE THREAD

**Issue by benlanier** [micktwomey/elmo-8#1]
Viewing Basic.elm from the examples on iOS Safari appears to draw the bird sprite correctly, but neither text (via `Console.print`) nor pixel (via `Console.putPixel`) seem to have any result.

I've circumvented it for now by saving out the font and palette data uri's back to png's and replacing calls to `WebGL.loadTexture` with the resulting filenames in place of the data uri arguments, but I wonder why Safari on iOS 10.1 has issues loading the font and palette in that way.

**Comment by michael-twomey-rockalltech** [comment]
Thanks for the bug report! I've been running into a lot of issues like this, webgl is a little inconsistent across devices. Hopefully it has a proper errors I can hook into (I'm ignoring texture errors at the moment). I was really hoping the data uri would work across the board as it makes the library much easier to work with.
